export const extensionCopy = {
  en: {
    home: 'Home', label: 'ReplayGlows extension', guide: 'Practical guide', article: 'Try a review workflow',
    title: 'Your pace. Your notes. Right in the browser.',
    description: 'Adjust playback across supported websites, keep one tab at its own pace and revisit YouTube passages with timestamped notes.',
    intro: 'Set a shared listening speed for HTML5 video and audio. When a passage needs more attention, pin its tab to a different speed. On YouTube, connect your review to the bookmarks you already saved.',
    availability: 'Public installation is being prepared. There is no public download link on this page yet.',
    preview: 'Illustration of the playback controls', global: 'Shared speed', pinned: 'Another tab, pinned',
    cards: [
      ['One pace across tabs', 'Choose a base speed from 0.25× to 4×. Supported unpinned tabs follow it, including newly discovered media. The popup offers a slider, 0.5× / 1× / 1.5× / 2× presets and a favorite speed.'],
      ['An exception when you need it', 'Pin a tab inside ReplayGlows to keep its own rate while the others follow your base speed. Unpin it to rejoin the current shared speed. This is separate from pinning a tab in Chrome.'],
      ['Turn timestamps into a passage', 'On YouTube, keep timestamped bookmarks and notes. Choose two bookmarks on the current video as the beginning and end of a temporary A–B loop, or mark the positions while watching.'],
      ['Controls within reach', 'Configure playback shortcuts alongside bookmark shortcuts. Hold the boost shortcut to accelerate temporarily, then release it to return to your pace. Text fields are protected from playback shortcuts.'],
    ],
    boundaryTitle: 'Two tools for different parts of your workflow',
    boundary: 'The extension works on browser pages without an app sign-in. Its bookmarks and settings stay local to the extension. The ReplayGlows web app has its own account and library: automatic synchronization between the two is not available.',
    compatibilityTitle: 'Playback across sites. Notes on YouTube.',
    compatibility: 'Playback controls apply to accessible HTML5 video and audio on HTTP and HTTPS pages. Notes remain YouTube-specific. Browser-protected pages, file URLs and inaccessible players are not supported; some websites enforce their own playback rate.',
    guideTitle: 'Use the ReplayGlows extension',
    guideDescription: 'Learn shared speed, tab pins, shortcuts and temporary A–B loops, with recovery steps for unavailable media.',
    guideIntro: 'This guide describes the current extension controls. Public installation is being prepared; if you already have a test version installed, open it from the browser toolbar while a media page is active.',
    sections: [
      ['1. Set your usual pace', 'Open a supported page with video or audio, then open ReplayGlows. Use the bottom playback card to select a preset or move the slider. With Global scope, the rate becomes your shared base for supported unpinned tabs. You can set your favorite rate and shortcut increment in Options.'],
      ['2. Slow down just one tab', 'Pin the current tab in the playback card, then choose its speed. Other unpinned tabs keep following the shared rate. Unpin to join the latest global rate. Pins survive page navigation within the session; closing the tab or restarting the browser clears them. Your base speed and preferences remain saved locally.'],
      ['3. Repeat a passage', 'Expand “Répéter un passage · boucle A–B” in the playback card (the current extension interface is in French). On finite-duration media, use “Début A” at the start and “Fin B” at a later position. On the current YouTube video, select the “Début” and “Fin” bookmarks, then click “Répéter entre ces marque-pages”. Playback repeats between A and B. Clear the loop to stop repeating. Seeking outside the segment, changing the media or navigating away clears it too. The loop itself is not saved in your notes.'],
      ['4. Keep useful moments', 'YouTube bookmarks retain timestamps and notes so you can return later. JSON export downloads a file; Markdown export copies text to the clipboard. JSON import validates the file, then asks for confirmation before replacing all current bookmarks. Export a backup first if you need to keep the current records. A temporary loop or pinned-tab speed is not part of that export.'],
      ['5. Make shortcuts comfortable', 'Open Options to change playback shortcuts and the speed increment. Avoid combinations already assigned to bookmark actions: conflicts are rejected. Playback shortcuts ignore editable fields. Hold the boost key to accelerate temporarily; releasing it or leaving the page focus restores the effective rate.'],
      ['When controls are unavailable', 'Start the media, check that you are on a supported web page and reopen the popup. After updating the extension, refresh existing tabs. If controls are suspended, re-enable them. A restricted browser page or inaccessible player cannot be controlled. If a site forces its own rate, the displayed media state may differ from your requested rate.'],
    ],
    shortcutsTitle: 'Default playback shortcuts', action: 'Action', keys: 'Shortcut',
    shortcuts: ['Slower / faster', 'Reset to 1×', 'Favorite speed', 'Seek backward / forward', 'Hold to boost', 'Set A / set B', 'Clear loop', 'Suspend / resume controls'],
    next: 'Put it into practice', nextText: 'Follow a worked example using a difficult YouTube passage, two bookmarks and a slower pinned tab.',
    articlePath: '/blog/review-a-video-passage', back: 'Discover the extension', language: 'Français',
  },
  fr: {
    home: 'Accueil', label: 'Extension ReplayGlows', guide: 'Guide pratique', article: 'Essayer un parcours de révision',
    title: 'Votre rythme. Vos notes. Dans le navigateur.',
    description: 'Réglez la lecture sur les sites compatibles, gardez un onglet à son propre rythme et retrouvez les passages YouTube grâce à vos notes horodatées.',
    intro: 'Choisissez une vitesse commune pour les vidéos et les fichiers audio HTML5. Lorsqu’un passage demande plus d’attention, épinglez son onglet à une autre vitesse. Sur YouTube, appuyez votre révision sur les marque-pages déjà enregistrés.',
    availability: 'L’installation publique est en préparation. Cette page ne propose pas encore de lien de téléchargement public.',
    preview: 'Illustration des commandes de lecture', global: 'Vitesse globale', pinned: 'Autre onglet épinglé',
    cards: [
      ['Un rythme commun à vos onglets', 'Choisissez une vitesse de base entre 0,25× et 4×. Les onglets compatibles non épinglés la suivent, y compris pour les nouveaux médias détectés. Le popup propose un curseur, les préréglages 0,5× / 1× / 1,5× / 2× et une vitesse favorite.'],
      ['Une exception quand il le faut', 'Épinglez un onglet dans ReplayGlows pour lui donner sa propre vitesse pendant que les autres suivent la vitesse globale. Désépinglez-le pour retrouver la vitesse commune actuelle. Ce réglage est distinct de l’épinglage des onglets dans Chrome.'],
      ['Des horodatages qui délimitent un passage', 'Sur YouTube, conservez vos marque-pages et vos notes horodatées. Choisissez deux marque-pages de la vidéo courante pour délimiter une boucle A–B temporaire, ou posez les bornes pendant la lecture.'],
      ['Des commandes à portée de main', 'Configurez les raccourcis de lecture à côté de ceux des marque-pages. Maintenez le raccourci d’accélération temporaire, puis relâchez-le pour retrouver votre rythme. Les champs de saisie sont protégés des raccourcis de lecture.'],
    ],
    boundaryTitle: 'Deux outils pour des moments différents',
    boundary: 'L’extension fonctionne dans les pages du navigateur sans connexion à l’application. Ses marque-pages et ses réglages restent stockés localement. L’application web ReplayGlows possède son propre compte et sa bibliothèque : la synchronisation automatique entre les deux n’est pas disponible.',
    compatibilityTitle: 'La lecture sur plusieurs sites. Les notes sur YouTube.',
    compatibility: 'Les commandes de lecture s’appliquent aux vidéos et fichiers audio HTML5 accessibles sur les pages HTTP et HTTPS. Les notes restent propres à YouTube. Les pages protégées du navigateur, les URL de fichiers et les lecteurs inaccessibles ne sont pas pris en charge ; certains sites imposent leur propre vitesse.',
    guideTitle: 'Utiliser l’extension ReplayGlows',
    guideDescription: 'Découvrez la vitesse globale, les onglets épinglés, les raccourcis et les boucles A–B temporaires, avec des solutions lorsque le média est indisponible.',
    guideIntro: 'Ce guide décrit les commandes actuelles de l’extension. L’installation publique est en préparation ; si vous disposez déjà d’une version de test, ouvrez-la depuis la barre du navigateur avec une page contenant un média au premier plan.',
    sections: [
      ['1. Choisir votre rythme habituel', 'Ouvrez une page compatible contenant une vidéo ou un fichier audio, puis ReplayGlows. Dans l’encart de lecture en bas du popup, choisissez un préréglage ou déplacez le curseur. Avec la portée Globale, cette vitesse devient la base commune des onglets compatibles non épinglés. Les Options permettent de choisir votre vitesse favorite et le pas des raccourcis.'],
      ['2. Ralentir un seul onglet', 'Épinglez l’onglet courant dans l’encart de lecture, puis choisissez sa vitesse. Les autres onglets non épinglés continuent de suivre la vitesse globale. Désépinglez-le pour rejoindre la vitesse commune actuelle. L’épinglage survit à la navigation pendant la session ; fermer l’onglet ou redémarrer le navigateur l’efface. Votre vitesse de base et vos préférences restent enregistrées localement.'],
      ['3. Répéter un passage', 'Ouvrez « Répéter un passage · boucle A–B » dans l’encart de lecture. Sur un média de durée finie, utilisez « Début A » au début et « Fin B » à une position ultérieure. Sur la vidéo YouTube courante, sélectionnez les marque-pages « Début » et « Fin », puis cliquez sur « Répéter entre ces marque-pages ». La lecture se répète entre A et B. Effacez la boucle pour arrêter la répétition. Sortir du segment, changer de média ou quitter la page l’efface également. La boucle elle-même n’est pas enregistrée dans les notes.'],
      ['4. Conserver les moments utiles', 'Les marque-pages YouTube gardent les horodatages et les notes pour y revenir plus tard. L’export JSON télécharge un fichier ; l’export Markdown copie le texte dans le presse-papiers. L’import JSON valide le fichier, puis demande confirmation avant de remplacer tous les marque-pages actuels. Exportez d’abord une sauvegarde si vous souhaitez conserver les données présentes. Une boucle temporaire ou la vitesse d’un onglet épinglé ne fait pas partie de cet export.'],
      ['5. Adapter les raccourcis', 'Ouvrez les Options pour modifier les raccourcis de lecture et le pas de vitesse. Évitez les combinaisons déjà affectées aux marque-pages : les conflits sont refusés. Les raccourcis de lecture ignorent les champs éditables. Maintenez la touche d’accélération temporaire ; la relâcher ou quitter le focus de la page rétablit la vitesse du contexte.'],
      ['Si les commandes sont indisponibles', 'Lancez le média, vérifiez que la page est compatible et rouvrez le popup. Après une mise à jour de l’extension, actualisez les onglets déjà ouverts. Si les commandes sont suspendues, réactivez-les. Une page protégée du navigateur ou un lecteur inaccessible ne peut pas être contrôlé. Si le site impose son propre rythme, la vitesse observée peut différer de celle demandée.'],
    ],
    shortcutsTitle: 'Raccourcis de lecture par défaut', action: 'Action', keys: 'Raccourci',
    shortcuts: ['Ralentir / accélérer', 'Revenir à 1×', 'Vitesse favorite', 'Reculer / avancer', 'Maintenir pour accélérer', 'Placer A / placer B', 'Effacer la boucle', 'Suspendre / reprendre les commandes'],
    next: 'Passer à la pratique', nextText: 'Suivez un exemple avec un passage YouTube difficile, deux marque-pages et un onglet épinglé à une vitesse plus lente.',
    articlePath: '/fr/blog/reviser-un-passage-video', back: 'Découvrir l’extension', language: 'English',
  },
} as const
