const ENGLISH_ERRORS: Record<string, string> = {
  'URL vidéo YouTube invalide': 'Invalid YouTube video URL', 'Marque-page invalide': 'Invalid bookmark', 'Marque-page invalide : URL, temps ou note': 'Invalid bookmark: URL, time, or note', 'Le fichier doit contenir une liste de marque-pages': 'The file must contain a list of bookmarks', 'Un marque-page existe déjà à ce moment. Modifiez sa note dans la liste.': 'A bookmark already exists at this moment. Edit its note in the list.', 'Ce marque-page n’existe plus. Rechargez la liste.': 'This bookmark no longer exists. Reload the list.', 'Un marque-page existe déjà à ce moment.': 'A bookmark already exists at this moment.', 'Action non reconnue': 'Unknown action', 'Échec de sauvegarde': 'Unable to save',
  'Vitesse invalide (0,25–4×).': 'Invalid speed (0.25–4×).', 'Réglages invalides.': 'Invalid settings.', 'Activation invalide.': 'Invalid enabled state.', 'Incrément invalide (0,05–1).': 'Invalid step (0.05–1).', 'Raccourci invalide.': 'Invalid shortcut.', 'Modificateur répété.': 'Repeated modifier.', 'Deux commandes utilisent le même raccourci.': 'Two commands use the same shortcut.', 'Réponse média invalide.': 'Invalid media response.', 'Émetteur non autorisé.': 'Unauthorized sender.', 'Action réservée à l’interface.': 'Action reserved for the extension interface.', 'Enregistrement réservé aux pages.': 'Registration reserved for web pages.', 'Seule la suspension est autorisée depuis une page.': 'Only pausing controls is allowed from a web page.', 'Ce raccourci est déjà utilisé pour les marque-pages.': 'This shortcut is already used for bookmarks.', 'Épinglage invalide.': 'Invalid pin state.', 'Spécifiez une vitesse ou un incrément.': 'Specify a speed or a step.', 'Incrément invalide.': 'Invalid step.', 'Commande inconnue.': 'Unknown command.', 'Bornes de boucle invalides.': 'Invalid loop bounds.', 'Aucun média accessible dans cet onglet.': 'No accessible media in this tab.', 'Le média ne répond pas.': 'The media is not responding.', 'Le média est déconnecté. Rechargez la page.': 'The media disconnected. Reload the page.', 'Action inconnue.': 'Unknown action.', 'Échec du contrôle de lecture.': 'Playback control failed.', 'Cette vitesse n’est pas prise en charge par ce lecteur.': 'This player does not support that speed.', 'Le site a modifié ou refusé la vitesse demandée.': 'The site changed or rejected the requested speed.', 'Aucun média disponible dans cet onglet.': 'No media is available in this tab.', 'Placez A avant la fin d’un média de durée finie.': 'Place A before the end of finite media.', 'Placez B après le point A.': 'Place B after point A.', 'Choisissez deux points valides, avec B après A.': 'Choose two valid points, with B after A.', 'Le navigateur a refusé la lecture.': 'The browser refused playback.',
}
export async function localizeRuntimeError(message: string): Promise<string> {
  const { language = 'auto' } = await chrome.storage.local.get('language')
  const selected = language === 'fr' || (language === 'auto' && navigator.languages.some(item => item.toLowerCase().startsWith('fr'))) ? 'fr' : 'en'
  return selected === 'fr' ? message : ENGLISH_ERRORS[message] ?? message
}
