#!/bin/bash
set -e

CONVEX_DART_DEFINE="${CONVEX_URL:-}"
CLERK_PUBLISHABLE_KEY_DART_DEFINE="${CLERK_PUBLISHABLE_KEY:-}"
CLERK_SIGN_IN_URL_DART_DEFINE="${CLERK_SIGN_IN_URL:-/sign-in}"
CLERK_SIGN_UP_URL_DART_DEFINE="${CLERK_SIGN_UP_URL:-/sign-up}"
REPLAYGLOWS_PRODUCT_ID_DART_DEFINE="${REPLAYGLOWS_PRODUCT_ID:-${REPLAYGLOWZ_PRODUCT_ID:-replayglows}}"
REPLAYGLOWS_LEGACY_PRODUCT_IDS_DART_DEFINE="${REPLAYGLOWS_LEGACY_PRODUCT_IDS:-${REPLAYGLOWZ_LEGACY_PRODUCT_IDS:-replayglowz,tubeflow}}"
REPLAYGLOWS_ACCOUNT_CENTER_URL_DART_DEFINE="${REPLAYGLOWS_ACCOUNT_CENTER_URL:-${REPLAYGLOWZ_ACCOUNT_CENTER_URL:-https://winflows.com/account}}"
REPLAYGLOWS_APP_URL_DART_DEFINE="${REPLAYGLOWS_APP_URL:-${REPLAYGLOWZ_APP_URL:-https://app.replayglows.com}}"
BUILD_COMMIT_SHA_DART_DEFINE="${BUILD_COMMIT_SHA:-${VERCEL_GIT_COMMIT_SHA:-$(git rev-parse --short HEAD 2>/dev/null || echo unknown)}}"
BUILD_ID_DART_DEFINE="${BUILD_ID:-${GITHUB_RUN_ID:-${VERCEL_GIT_COMMIT_SHA:-$BUILD_COMMIT_SHA_DART_DEFINE}}}"
BUILD_ENVIRONMENT_DART_DEFINE="${BUILD_ENVIRONMENT:-${VERCEL_ENV:-local}}"
BUILD_TIMESTAMP_DART_DEFINE="${BUILD_TIMESTAMP:-$(date -u +%Y-%m-%dT%H:%M:%SZ)}"
BUILD_AT_UTC_DART_DEFINE="${BUILD_AT_UTC:-$BUILD_TIMESTAMP_DART_DEFINE}"
BUILD_AT_PARIS_DART_DEFINE="${BUILD_AT_PARIS:-$(TZ=Europe/Paris date -d "$BUILD_AT_UTC_DART_DEFINE" '+%Y-%m-%d %H:%M' 2>/dev/null || TZ=Europe/Paris date '+%Y-%m-%d %H:%M')}"
SENTRY_DSN_DART_DEFINE="${SENTRY_DSN:-}"
SENTRY_ENVIRONMENT_DART_DEFINE="${SENTRY_ENVIRONMENT:-$BUILD_ENVIRONMENT_DART_DEFINE}"
SENTRY_RELEASE_DART_DEFINE="${SENTRY_RELEASE:-replayglows_app@$BUILD_COMMIT_SHA_DART_DEFINE}"
SENTRY_TRACES_SAMPLE_RATE_DART_DEFINE="${SENTRY_TRACES_SAMPLE_RATE:-0}"
SENTRY_DEBUG_DART_DEFINE="${SENTRY_DEBUG:-false}"
FLUTTER_VERSION="${FLUTTER_VERSION:-3.47.1}"
CACHE_ROOT="${VERCEL_CACHE_DIR:-.vercel/cache}"
export PUB_CACHE="${PUB_CACHE:-$CACHE_ROOT/pub-cache}"
FLUTTER_BIN="${FLUTTER_BIN:-flutter}"
if [ -x "$CACHE_ROOT/flutter-$FLUTTER_VERSION/bin/flutter" ]; then
  FLUTTER_BIN="$CACHE_ROOT/flutter-$FLUTTER_VERSION/bin/flutter"
elif [ -x "flutter/bin/flutter" ]; then
  FLUTTER_BIN="flutter/bin/flutter"
fi

"$FLUTTER_BIN" build web \
  "--dart-define=CONVEX_URL=$CONVEX_DART_DEFINE" \
  "--dart-define=CLERK_PUBLISHABLE_KEY=$CLERK_PUBLISHABLE_KEY_DART_DEFINE" \
  "--dart-define=CLERK_SIGN_IN_URL=$CLERK_SIGN_IN_URL_DART_DEFINE" \
  "--dart-define=CLERK_SIGN_UP_URL=$CLERK_SIGN_UP_URL_DART_DEFINE" \
  "--dart-define=REPLAYGLOWS_PRODUCT_ID=$REPLAYGLOWS_PRODUCT_ID_DART_DEFINE" \
  "--dart-define=REPLAYGLOWS_LEGACY_PRODUCT_IDS=$REPLAYGLOWS_LEGACY_PRODUCT_IDS_DART_DEFINE" \
  "--dart-define=REPLAYGLOWS_ACCOUNT_CENTER_URL=$REPLAYGLOWS_ACCOUNT_CENTER_URL_DART_DEFINE" \
  "--dart-define=REPLAYGLOWS_APP_URL=$REPLAYGLOWS_APP_URL_DART_DEFINE" \
  "--dart-define=BUILD_COMMIT_SHA=$BUILD_COMMIT_SHA_DART_DEFINE" \
  "--dart-define=BUILD_ID=$BUILD_ID_DART_DEFINE" \
  "--dart-define=BUILD_ENVIRONMENT=$BUILD_ENVIRONMENT_DART_DEFINE" \
  "--dart-define=BUILD_TIMESTAMP=$BUILD_TIMESTAMP_DART_DEFINE" \
  "--dart-define=BUILD_AT_PARIS=$BUILD_AT_PARIS_DART_DEFINE" \
  "--dart-define=BUILD_AT_UTC=$BUILD_AT_UTC_DART_DEFINE" \
  "--dart-define=SENTRY_DSN=$SENTRY_DSN_DART_DEFINE" \
  "--dart-define=SENTRY_ENVIRONMENT=$SENTRY_ENVIRONMENT_DART_DEFINE" \
  "--dart-define=SENTRY_RELEASE=$SENTRY_RELEASE_DART_DEFINE" \
  "--dart-define=SENTRY_TRACES_SAMPLE_RATE=$SENTRY_TRACES_SAMPLE_RATE_DART_DEFINE" \
  "--dart-define=SENTRY_DEBUG=$SENTRY_DEBUG_DART_DEFINE" \
  2>&1 \
|| {
  echo '=== DART ERRORS ==='
  "$FLUTTER_BIN" analyze --no-pub lib web 2>&1 | tail -50
  exit 1
}
