allowBuilds:
  '@parcel/watcher': true
  esbuild: true
minimumReleaseAgeExclude:
  - autoprefixer@10.5.5
  - browserslist@4.28.9
  - eslint@10.10.0
onlyBuiltDependencies:
  - esbuild
  - '@parcel/watcher'

overrides:
  yaml: ^2.8.3
