import assert from 'node:assert/strict'
import { mkdtempSync, mkdirSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
const { chromium } = await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href)
const output = process.env.DISCOVERY_PROOF_DIR ?? join(tmpdir(), 'rg-discovery-proof')
mkdirSync(output, { recursive: true })
const extension = resolve('dist')
const context = await chromium.launchPersistentContext(mkdtempSync(join(tmpdir(), 'rg-discovery-')), {
  executablePath: process.env.PLAYWRIGHT_CHROMIUM, headless: true,
  args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`, '--autoplay-policy=no-user-gesture-required'],
})
const wav = Buffer.alloc(44 + 8000 * 2 * 30)
wav.write('RIFF'); wav.writeUInt32LE(wav.length - 8,4); wav.write('WAVEfmt ',8)
wav.writeUInt32LE(16,16); wav.writeUInt16LE(1,20); wav.writeUInt16LE(1,22)
wav.writeUInt32LE(8000,24); wav.writeUInt32LE(16000,28); wav.writeUInt16LE(2,32); wav.writeUInt16LE(16,34)
wav.write('data',36); wav.writeUInt32LE(wav.length-44,40)
const html = `<html><head><title>Discovery fixture</title></head><body><h1>Video</h1><video controls src="data:audio/wav;base64,${wav.toString('base64')}"></video></body></html>`
const errors = []
context.setDefaultTimeout(15000)
try {
  const worker = context.serviceWorkers()[0] ?? await context.waitForEvent('serviceworker')
  const id = new URL(worker.url()).host
  const options = await context.newPage()
  await options.goto(`chrome-extension://${id}/src/options/options.html`)
  const stored = name => options.evaluate(async name => (await chrome.storage.local.get(name))[name], `discovery.v1.${name}`)
  const send = request => options.evaluate(request => chrome.runtime.sendMessage(request), request)
  await context.route('https://example.com/discovery', route => route.fulfill({ contentType:'text/html',body:html }))
  await context.route('https://www.youtube.com/watch?*', route => route.fulfill({ contentType:'text/html',body:html }))
  const media = await context.newPage(); await media.goto('https://example.com/discovery')
  await media.waitForFunction(() => document.querySelector('video').duration === 30)
  let popup
  async function open(target=media) {
    if (popup && !popup.isClosed()) await popup.close()
    popup = await context.newPage(); await target.bringToFront()
    await popup.goto(`chrome-extension://${id}/src/popup/index.html`)
    await popup.setViewportSize({width:432,height:600})
    popup.on('pageerror', e => errors.push(e.message))
    await popup.getByRole('button',{name:'Découvrir / Aide',exact:true}).waitFor()
    return popup
  }
  await open()
  await popup.getByText('0 / 5 réussites confirmées').waitFor()
  await popup.getByRole('button',{name:'Pour plus tard',exact:true}).click()
  assert.equal(await popup.locator('#discovery-topic').inputValue(),'pin')
  assert.equal(await stored('speed'),undefined)
  await open()
  assert.equal(await popup.locator('#discovery-topic').inputValue(),'pin')
  await popup.locator('#discovery-topic').selectOption('speed')
  await popup.getByRole('button',{name:'Reprendre cet exercice'}).click()
  await popup.getByRole('button',{name:'1.5×',exact:true}).click()
  await popup.getByText('1 / 5 réussites confirmées').waitFor()
  assert.equal(await stored('speed'),true)
  await popup.getByRole('button',{name:'Épingler',exact:true}).click()
  await popup.getByText('2 / 5 réussites confirmées').waitFor()
  await popup.locator('#discovery-topic').selectOption('loop')
  await popup.getByRole('button',{name:'Aller aux commandes'}).click()
  await media.evaluate(() => {document.querySelector('video').currentTime=2})
  await popup.getByRole('button',{name:'Début A',exact:true}).click()
  await popup.getByRole('button',{name:'Fin B',exact:true}).click()
  assert.equal(await stored('loop'),undefined)
  await media.evaluate(() => {document.querySelector('video').currentTime=5})
  await popup.getByRole('button',{name:'Fin B',exact:true}).click()
  await popup.getByRole('button',{name:'Découvrir / Aide',exact:true}).click()
  await popup.getByText('3 / 5 réussites confirmées').waitFor()
  await popup.getByRole('button',{name:'Masquer les conseils'}).click()
  await open()
  assert.equal(await popup.locator('.sg-discovery').count(),0)
  await popup.getByRole('button',{name:'Découvrir / Aide',exact:true}).click()
  await popup.getByRole('heading',{name:'Votre prochain petit pas'}).waitFor()
  assert.equal(await popup.evaluate(() => document.activeElement.tagName),'H2')
  const bookmark = {url:'https://www.youtube.com/watch?v=rgDiscovery',time:2,note:'Mon idée'}
  assert.ok((await send({action:'addBookmark',bookmark:{...bookmark,time:-1}})).error)
  assert.equal(await stored('note'),undefined)
  await send({action:'addBookmark',bookmark})
  await popup.getByText('4 / 5 réussites confirmées').waitFor()
  await popup.locator('#discovery-topic').selectOption('opened')
  await popup.getByRole('button',{name:'Choisir un marque-page'}).click()
  await popup.evaluate(() => { chrome.tabs.create = async () => { throw Error('fixture navigation failure') } })
  await popup.getByRole('button',{name:'Vidéo YouTube · 0:02',exact:true}).click()
  await popup.getByText('Impossible d’ouvrir la vidéo.',{exact:false}).waitFor()
  assert.equal(await stored('opened'),undefined)
  await open()
  await popup.getByRole('button',{name:'Vidéo YouTube · 0:02',exact:true}).click()
  await options.waitForFunction(async () => (await chrome.storage.local.get('discovery.v1.opened'))['discovery.v1.opened']===true)
  await options.evaluate(() => chrome.storage.local.set({hotkeys:{'add-bookmark':'CTRL+SHIFT+Y'}}))
  await open()
  await popup.locator('#discovery-topic').selectOption('note')
  await popup.getByText('CTRL+SHIFT+Y',{exact:true}).waitFor()
  await popup.evaluate(() => { chrome.storage.local.set = async () => { throw Error('fixture storage failure') } })
  await popup.getByRole('button',{name:'Masquer les conseils'}).click()
  await popup.getByText('Progression non enregistrée.',{exact:false}).waitFor()
  assert.equal(await popup.locator('.sg-discovery').isVisible(),true)
  await open()
  await popup.screenshot({path:join(output,'guide-notes.png')})
  console.log('PASS real commands, invalid loop/save, progress, skip/resume, hide/reopen, configured shortcut, note/open milestones')

  // A refusing media element must never earn a speed milestone.
  await options.evaluate(() => chrome.storage.local.remove('discovery.v1.speed'))
  const cdp = await context.newCDPSession(media)
  const worlds = []
  cdp.on('Runtime.executionContextCreated', ({context}) => worlds.push(context))
  await cdp.send('Runtime.enable')
  const isolated = worlds.find(world => world.name.includes(id) || world.origin === `chrome-extension://${id}`)
  assert.ok(isolated, JSON.stringify(worlds))
  await cdp.send('Runtime.evaluate', {contextId:isolated.id,expression:`Object.defineProperty(document.querySelector('video'),'playbackRate',{configurable:true,get:()=>1,set:()=>{throw Error('rate refused')}})`})
  await open()
  await popup.getByRole('button',{name:'2×',exact:true}).click()
  await popup.locator('.sg-playback-error').first().waitFor()
  assert.equal(await stored('speed'),undefined)
  const empty=await context.newPage(); await empty.goto('about:blank')
  await open(empty)
  await popup.getByText('Aucun média accessible.',{exact:false}).waitFor()
  assert.equal(await popup.getByRole('button',{name:'1.5×',exact:true}).isDisabled(),true)
  assert.equal(await stored('speed'),undefined)
  console.log('PASS rejected speed and protected/no-media page cannot complete speed')
  await options.evaluate(() => chrome.storage.local.set({playbackSettings:{rate:9,keys:{faster:'BAD'}},hotkeys:{}}))
  await open()
  await popup.locator('#discovery-topic').selectOption('note')
  await popup.getByText('Désactivé dans les réglages',{exact:true}).waitFor()
  await popup.getByText('⚡ Favori, boost et raccourcis',{exact:true}).click()
  await popup.getByText('ALT+SHIFT+D',{exact:true}).waitFor()
  await send({action:'rg:settings',settings:{enabled:false}})
  await popup.locator('#discovery-topic').selectOption('speed')
  await popup.getByText('Les commandes sont suspendues.',{exact:false}).waitFor()
  console.log('PASS failed navigation/storage recovery, malformed effective shortcuts, suspension guidance')

  // Native action-popup proof is owned by discovery-native.mjs (Chrome exposes it as a CDP target).
  assert.deepEqual(errors,[])
  console.log(`PROOF_DIR ${output}`)
} finally { await context.close() }
