import assert from 'node:assert/strict'
import { mkdtempSync, mkdirSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

const { chromium } = await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href)
const output = process.env.OPTIONS_PROOF_DIR ?? join(tmpdir(), 'rg-options-design')
mkdirSync(output, { recursive: true })
const extension = resolve('dist')
const context = await chromium.launchPersistentContext(mkdtempSync(join(tmpdir(), 'rg-options-')), {
  executablePath: process.env.PLAYWRIGHT_CHROMIUM, headless: true,
  args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`],
})
try {
  const worker = context.serviceWorkers()[0] ?? await context.waitForEvent('serviceworker')
  const page = await context.newPage()
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto(`chrome-extension://${new URL(worker.url()).host}/src/options/options.html`)
  await page.evaluate(() => chrome.storage.local.set({ language: 'fr' }))
  await page.locator('.sg-playback-fields:not([disabled])').first().waitFor()
  assert.equal(await page.locator('.sg-playback-fields').count(), 2)
  for (const [width, columns] of [[1600, 3], [1000, 2], [390, 1]]) {
    await page.setViewportSize({ width, height: 1000 })
    assert.equal(await page.locator('.sg-options-grid').evaluate(el => getComputedStyle(el).gridTemplateColumns.split(' ').length), columns)
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `No horizontal overflow at ${width}`)
    assert.equal(await page.locator('.sg-options-guide').getAttribute('open'), null)
    if (columns === 2) {
      const [first, , third] = await page.locator('.sg-options-column').evaluateAll(elements => elements.map(el => ({ top: el.getBoundingClientRect().top, bottom: el.getBoundingClientRect().bottom })))
      assert.ok(third.top - first.bottom < 30, 'Tablet bookmarks follow the left column without a large gap')
    }
    assert.equal(await page.getByRole('button', { name: 'Enregistrer la lecture', exact: true }).count(), 0)
    const row = page.locator('.hotkey-input').first()
    const labelBox = await row.locator(':scope > .t').boundingBox()
    const fieldBox = await row.locator('.sg-hotkey-controls').boundingBox()
    if (width === 1600) assert.ok(fieldBox.x > labelBox.x + labelBox.width, 'Wide shortcut field sits to the right of its label')
    if (width === 390) assert.ok(fieldBox.y >= labelBox.y + labelBox.height, 'Narrow shortcut field wraps below its label')
    assert.equal(await page.locator('.sg-hotkey-clear svg').count(), 16)
    assert.ok((await page.locator('.sg-hotkey-clear').allTextContents()).every(text => text.trim() === ''))
    await page.screenshot({ path: join(output, `options-fr-${width}.png`), fullPage: true })
  }
  console.log('PASS responsive 3/2/1 columns, no overflow, collapsed help and no save button')
  await page.setViewportSize({ width: 1600, height: 1000 })
  const forms = page.locator('.sg-playback-form')
  const playbackRows = forms.nth(1).locator('.hotkey-input')
  for (let index = 0; index < await playbackRows.count(); index++) {
    const row = playbackRows.nth(index)
    await row.locator('.sg-hotkey-clear svg').click()
    assert.equal(await row.locator('input').inputValue(), '', `Playback shortcut ${index} clears by clicking the SVG itself`)
    assert.equal(await row.locator('input').getAttribute('placeholder'), null, 'Cleared playback input is visually empty')
  }
  await page.waitForFunction(async () => Object.values((await chrome.runtime.sendMessage({ action: 'rg:context' })).settings.keys).every(key => key === ''))
  await page.reload()
  await page.locator('.sg-playback-fields:not([disabled])').first().waitFor()
  for (const input of await forms.nth(1).locator('input[readonly]').all()) assert.equal(await input.inputValue(), '')
  await page.getByRole('button', { name: 'Raccourcis par défaut', exact: true }).click()
  await page.waitForFunction(async () => (await chrome.runtime.sendMessage({ action: 'rg:context' })).settings.keys.slower === 'ALT+SHIFT+S')

  const favorite = page.getByRole('spinbutton', { name: 'Vitesse favorite', exact: true })
  await favorite.fill('1.75'); await favorite.press('Tab')
  await page.waitForFunction(async () => (await chrome.runtime.sendMessage({ action: 'rg:context' })).settings.favorite === 1.75)
  assert.equal(await forms.first().locator('input[type=checkbox]').first().evaluate(el => el === document.activeElement), true, 'Tab follows the visible order')
  const checkbox = forms.first().locator('input[type=checkbox]').first()
  const checked = !(await checkbox.isChecked()); await checkbox.setChecked(checked)
  const step = page.getByRole('spinbutton', { name: 'Pas des raccourcis', exact: true })
  await step.fill('0.15'); await step.press('Tab')
  await page.waitForFunction(async () => (await chrome.runtime.sendMessage({ action: 'rg:context' })).settings.step === 0.15)
  const playbackKey = forms.nth(1).locator('input[readonly]').first()
  await playbackKey.press('Alt+Shift+J')
  await page.waitForFunction(async () => (await chrome.runtime.sendMessage({ action: 'rg:context' })).settings.keys.slower === 'ALT+SHIFT+J')
  await page.reload(); await page.locator('.sg-playback-fields:not([disabled])').first().waitFor()
  assert.equal(await favorite.inputValue(), '1.75')
  assert.equal(await step.inputValue(), '0.15')
  assert.equal(await checkbox.isChecked(), checked)
  assert.equal(await playbackKey.inputValue(), 'ALT+SHIFT+J')
  await playbackKey.press('Alt+B')
  await page.getByRole('alert').waitFor()
  assert.equal(await page.evaluate(async () => (await chrome.runtime.sendMessage({ action: 'rg:context' })).settings.keys.slower), 'ALT+SHIFT+J')
  await page.getByRole('button', { name: 'Raccourcis par défaut', exact: true }).click()
  await page.waitForFunction(async () => (await chrome.runtime.sendMessage({ action: 'rg:context' })).settings.keys.slower === 'ALT+SHIFT+S')
  await page.getByRole('button', { name: 'Effacer le raccourci : Ralentir', exact: true }).click()
  assert.equal(await playbackKey.inputValue(), '', 'Playback field clears immediately without reload')
  await page.waitForFunction(async () => (await chrome.runtime.sendMessage({ action: 'rg:context' })).settings.keys.slower === '')
  await page.getByRole('button', { name: 'Raccourcis par défaut', exact: true }).click()
  await page.waitForFunction(async () => (await chrome.runtime.sendMessage({ action: 'rg:context' })).settings.keys.slower === 'ALT+SHIFT+S')
  const bookmarkKey = page.locator('.sg-bookmark-shortcuts input').first()
  await bookmarkKey.press('Alt+Shift+S')
  await page.getByText('Ce raccourci est déjà utilisé pour la lecture ou un autre marque-page.', { exact: true }).waitFor()
  assert.equal(await page.evaluate(async () => (await chrome.storage.local.get('hotkeys')).hotkeys['add-bookmark']), 'ALT+B')
  await page.getByRole('button', { name: 'Effacer le raccourci : Ajouter un marque-page', exact: true }).click()
  assert.equal(await bookmarkKey.inputValue(), '', 'Bookmark field clears immediately without reload')
  assert.ok(!(await bookmarkKey.getAttribute('placeholder'))?.includes('ALT'), 'Cleared field must not show the old shortcut as placeholder')
  await page.waitForFunction(async () => (await chrome.storage.local.get('hotkeys')).hotkeys['add-bookmark'] === '')
  await page.reload()
  assert.equal(await bookmarkKey.inputValue(), '')
  await page.getByLabel('Masquer les notes par défaut :', { exact: true }).check()
  await page.waitForFunction(async () => (await chrome.storage.local.get('hideNotesByDefault')).hideNotesByDefault === true)
  console.log('PASS autosave, keyboard order, reload persistence, shortcut conflicts in both directions and reset')
  await page.getByRole('combobox', { name: 'Langue', exact: true }).selectOption('en')
  await page.getByRole('heading', { name: 'Playback and display', exact: true }).waitFor()
  await page.reload(); await page.locator('.sg-playback-fields:not([disabled])').first().waitFor()
  await page.screenshot({ path: join(output, 'options-en-1600.png'), fullPage: true })
  await page.locator('.sg-options-guide > summary').click()
  await page.getByText('Use one shared speed for videos and audio.', { exact: false }).waitFor()
  assert.ok(await page.locator('.sg-options-guide').getAttribute('open') !== null)
  assert.deepEqual(errors, [])
  console.log(`PASS language persistence, expanded help and no page errors\nPROOF_DIR ${output}`)
} finally { await context.close() }
